### ISSUE TITLE
Include documentation for setting upstream remote

### ISSUE THREAD

**Issue by gspetro-NOAA** [ufs-community/workflow-tools#137]
**Problem:** 
In `docs/Contributors_Guide/github_workflow.rst`, it says "The first command pulls changes from the original repository... that you see when you run *git remote -v* and that you set to upstream in step 4 above)." However, there is no step 4, and the docs do not indicate how to set upstream remote. A comment was added to the file indicating this problem. 

**Proposed Solution:**
Add an explanation for how to set upstream remote (possibly borrow from METplus docs). Delete comment.

**Comment by christinaholtNOAA** [comment]
We should point folks to authoritative docs on how to do things like this.
