### ISSUE TITLE
UW-271 Implement -q/-v/-d args as mutually exclusive

### ISSUE THREAD

**Issue by WeirAE** [ufs-community/workflow-tools#162]
**Description**
As we implement args more broadly across the toolset, it would be a better practice to limit some args as mutually exclusive at the evaluation stage

**Requirements**
Creating a mutually exclusive group during the parseargs such as
`group = parser.add_mutually_exclusive_group()`
allows us to throw a simple error at the start, preventing bad behavior. Argparse also shows the exclusivity on --h invocation, which makes it nicer for the user

**Acceptance Criteria (Definition of Done)**
Implement mutual exclusion for all argparser implementation

**Comment by venitahagerty** [comment]
Satisfied by Mayra's work in PR 245
