### ISSUE TITLE
CodeQL- 1 configuration not found

### ISSUE THREAD

**Issue by j-derrico** [ufs-community/workflow-tools#183]
On the [PR for the updated](https://github.com/ufs-community/workflow-tools/pull/180) users guide documentation one of the code checks, under GitHub code scanning, the CodeQL was neutral (did not pass or fail), GitHub generated the [following message](https://github.com/ufs-community/workflow-tools/runs/12133951859):

Warning: Code scanning cannot determine the alerts introduced by this pull request, because 1 configuration present on `refs/heads/develop` was not found:

Actions workflow (`codeql-analysis.yml`)
`❓  .github/workflows/codeql-analysis.yml:analyze/language:python`
No new alerts

When branch was actually merged into develop however CodeQL ran and all tests passed.

**Expected behavior**
CodeQL check on pull request should pass (expected in this case since only documentation was altered) or fail, no configurations should be missing since that file was not altered.

**Current behavior**

CodeQL check was 'neutral', stated 1 configuration was missing : ` .github/workflows/codeql-analysis.yml:analyze/language:python`

However, when branch was merged into develop all tests passed including CodeQL check

**To Reproduce**
Details on behavior can be found [here](https://github.com/ufs-community/workflow-tools/runs/12133951859)

**Context**
The only changes here were to the user's guide/documentation, all .rst files located in the docs directory, there was no change to any code and no change to the `.github/workflows/codeql-analysis.yml`, possibly this behavior was caused by documentation builds/updates

**Comment by christinaholtNOAA** [comment]
We removed Code-QL all together.
