### ISSUE TITLE
GHA for pylint may be broken

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/workflow-tools#22]
**Expected behavior**

The GHA test for pylint should catch items like "unused imports", and it doesn't seem to be doing that.

**Current behavior**
On PR #19, I couldn't find a reference to `ast.List` in `src/uwtools/generic_scheduler/scheduler.py` after being interested in how it was being used. I checked to see if all the tests passed, mainly the linter after expecting that it should, and found that pylint reported a 10/10. I expected that it should fail with something < 10.

**Machines affected**
GitHub Actions

**Comment by ryanlong1004** [comment]
Fixed in PR #31 .
