### ISSUE TITLE
UW-299 Add a forecast method that knows how to create a model_configure file

### ISSUE THREAD

**Issue by WeirAE** [ufs-community/workflow-tools#247]
**Description**
Add a forecast method that knows how to create a model_configure file

**Requirements**
Accepts a forecast object with a base model_config file and outputs a model_config

**Acceptance Criteria (Definition of Done)**
given: a configured forecast object that points to some base model_config file (template or YAML)
when: the create_model_config method is called
then: then the user-configured settings are applied to the input model_config file and a file is written to the run directory

when: testing the functionality
then: compare it against the one in the example run directory

**Additional context**
may call templater or set_config, may be a subsection of the full file
very close to how set_config works, may just send parameters to set_config
Related to #244

**Comment by venitahagerty** [comment]
Satisfied by Brian's work in PR 248
