### ISSUE TITLE
There are no tests for several methods in the config base class.

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/workflow-tools#254]
**Description**

We managed to let a few methods slip into the config base class (maybe others) without any unit tests. We should probably address that. 

**Acceptance Criteria (Definition of Done)**

Adequate unit tests contributed to the repo for the methods in config.py.

**Comment by maddenp-noaa** [comment]
`config.py` has 100% coverage in PR #263.

**Comment by christinaholtNOAA** [comment]
Now we have direct tests of every method in every class as of PR #340 thanks to @WeirAE finishing those up.
