### ISSUE TITLE
UW-8 Add a forecast method that stages files from known locations on disk.

### ISSUE THREAD

**Issue by NaureenBharwaniNOAA** [ufs-community/workflow-tools#261]
**Description**

The script needs to stage a list of files that are configuration specific (i.e., based on model resolution, regional vs global, ICS/LBCS model, etc).

This method should know what to do with static data files and cycle-specific data files. 

This method will likely need to be generic since most UFS components follow this "stage static and cycle-specific data" pattern. Perhaps the forecast-specific part is concerned with which information may need to be formatted – for example, forecast lead time, resolution, etc.

**Describe alternatives you've considered**

**Acceptance Criteria (Definition of Done)**

Scenario: I receive a set of parameters and need to make sure a set of files appears in the run directory

GIVEN: All files are assumed to be available on local disk. The default file names are set for required files.
WHEN: A properly structured configuration object is available to the forecast class
THEN: It will stage a set of files necessary to run the forecast as part of its run method.
 
GIVEN: The method is run
WHEN: A file is staged successfully
THEN: A log info message on where the files came from and where they were put is available.

GIVEN: A required file is unavailable at it configured location
WHEN: All files have attempted
THEN: The a status report of available/unavailable files will be logged, and the method will raise an exception.

**Additional context**

**Comment by christinaholtNOAA** [comment]
Fixed by PR #262
