### ISSUE TITLE
test_scheduler fails

### ISSUE THREAD

**Issue by benjamin-cash** [ufs-community/workflow-tools#33]
pytest is failing on test_scheduler with the following:

(uwtools) (base) login1.stampede2(1060)$ pytest
========================================================== test session starts ===========================================================
platform linux -- Python 3.7.9, pytest-7.1.1, pluggy-1.0.0
rootdir: /home1/02441/bcash/workflow-tools
collected 4 items                                                                                                                        

tests/test_scheduler.py .F..                                                                                                       [100%]

================================================================ FAILURES ================================================================
_____________________________________________________________ test_scheduler _____________________________________________________________

    def test_scheduler():
    
        expected = """#SBATCH scheduler=slurm
    #SBATCH --job-name=abcd
    #SBATCH extra_stuff=12345"""
    
        props = {"scheduler": "slurm", "job_name": "abcd", "extra_stuff": "12345"}
    
        js = JobScheduler.get_scheduler(props)
        actual = js.job_card.content()
    
>       assert actual == expected
E       AssertionError: assert '#SBATCH sche...ra_stuff12345' == '#SBATCH sche...a_stuff=12345'
E         - #SBATCH scheduler=slurm
E         ?                  -
E         + #SBATCH schedulerslurm
E           #SBATCH --job-name=abcd
E         - #SBATCH extra_stuff=12345
E         ?                    -
E         + #SBATCH extra_stuff12345

tests/test_scheduler.py:23: AssertionError
======================================================== short test summary info =========================================================
FAILED tests/test_scheduler.py::test_scheduler - AssertionError: assert '#SBATCH sche...ra_stuff12345' == '#SBATCH sche...a_stuff=12345'
====================================================== 1 failed, 3 passed in 0.08s =======================================================

Is this related to the discussion about the user needing to know when to supply '='?

**Comment by ryanlong1004** [comment]
I have the fix and the "=" solution in branch origin/refactor_known_unknown_props.

**Comment by ryanlong1004** [comment]
Fixed in PR #31
