### ISSUE TITLE
Use Github Actions to post pytest-cov report to Github Pages

### ISSUE THREAD

**Issue by ryanlong1004** [ufs-community/workflow-tools#54]
After Issue #53 is completed, update the Github Action to post an HTML report to Github Pages.

Keep only the most recent report.

This should only be triggered when pushing/merging to development.

`pytest-cov --cov-report html` is the base command to use to generate the report.  

Refer to docs in #53 for more information.

**Comment by ryanlong1004** [comment]
@ope-adejumo would you post a link?

**Comment by jprestop** [comment]
@ryanlong1004 I haven't been to many meetings and have been a bit out of the loop, however, I believe GitHub pages is currently disabled (see attached screenshot) and needs to be enabled before anything is visible.  I haven't done this in long while, but can try to help enable this functionality when desired, if needed.

<img width="1349" alt="Screen Shot 2022-05-12 at 1 52 43 PM" src="https://user-images.githubusercontent.com/11999822/168157456-2dabd4e6-774f-41e5-b922-506bec83d17f.png">

**Comment by ryanlong1004** [comment]
Fixed.
