### ISSUE TITLE
LSF scheduler needs work

### ISSUE THREAD

**Issue by aerorahul** [ufs-community/workflow-tools#57]
The LSF scheduler is a bit picky.
Specifically:
- The walltime request is `HH:MM`  instead of `HH:MM:SS`.  The input can be `HH:MM:SS` but the output needs to be in `HH:MM`. 
- The memory request is (I think in `kb` with no units). e.g. `#BSUB -R rusage[mem=1000]` is requesting 1MB of memory.  The input can be any units, but the output needs to be in `kb`.  @aerorahul will double check the correct units for this request.

**Expected behavior**
Correct syntax should be used when creating the job-card.

**Current behavior**
The user needs to know how to provide the request.  Failing which, the job is rejected by the scheduler.

**Machines affected**
Machines running IBM's LSF scheduler.

**Comment by ryanlong1004** [comment]
Closes #42 
Closes #48 
Closes #47
