### ISSUE TITLE
Pylint is currently disabling the need for doc blocks.

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/workflow-tools#87]
**Description**

We settled on documenting the code in-line with PEP-8 docstring conventions. Those are in large part missing and this was uncovered during a recent fix to the the linting workflows.

**Acceptance Criteria (Definition of Done)**
All pylint disable strings are removed for missing docstrings at the module, method, class level.

**Comment by ryanlong1004** [comment]
docstrings should be used in ```exceptions.py``` instead of ```pass```.

**Comment by christinaholtNOAA** [comment]
That's a great idea!

**Comment by benjamin-cash** [comment]
Did this ever get addressed?

**Comment by christinaholtNOAA** [comment]
Currently, no need for function docstrings in unittests, but they are required in all other code.
